services:
  postgres-service:
    container_name: postgres-service-container
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: system
      POSTGRES_PASSWORD: secret
